@startuml
class Usuario1
class Usuario2
class RobotAzul
class RobotRosa
class RobotNaranja
class RobotVerde
class Bomba
class BombaControlRemoto
class Explosion
class MuroSolido
class MuroDestruible
class Suelo
class Velocidad
class MasBombas
class MasFuego
class Escudo
class Guante
class Patada
class VidaExtra
class PistolaLaser
class ProyectilLaser
class Vehiculo
class Vida

Usuario1--->RobotAzul
Usuario2--->RobotNaranja


RobotAzul--->Personaje
RobotRosa--->Personaje
RobotNaranja--->Personaje
RobotVerde--->Personaje

RobotAzul*---Bomba
RobotRosa*---Bomba
RobotNaranja*---Bomba
RobotVerde*---Bomba

RobotAzul *-- "1" Vida
RobotRosa*--- "1" Vida
RobotNaranja*---"1" Vida
RobotVerde*--- "1" Vida

Class RobotAzul{
    -
    -
}
@enduml

